java:
  keyVaults:
    "s2s":
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-ctsc-work-allocation
  environment:
    TEST_ENDPOINTS_ENABLED: true
    SMTP_ENABLED: true
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
